name: pr-preview
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

    branches: [main, develop]
    paths: "sweet-client/*"

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  pages: write
  deployments: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: yarn install && yarn build

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.4.6
        with:
          source-dir: ./build/
